export const userDatabase = [
  {
    id: "5f95bc0bcf4c424ac739107f",
    firstname: "Francolino",
    lastname: "Mattos",
    email: "Franco@ohmnet.com",
    login: "franco",
    password: "franco",
    zipcode: "32116",
  },
  {
    id: "5f960e6fcf4c424ac76de721",
    firstname: "Donahue",
    lastname: "Morgan",
    email: "DMorgan@ohmnet.com",
    login: "donahue",
    password: "donahue",
    zipcode: "32116",
  },
  {
    id: "5f960efacf4c424ac76e3b44",
    firstname: "Nabeel",
    lastname: "Yousef",
    email: "nabeel_yousef@daytonastate.edu",
    login: "Nabeel",
    password: "Nabeel1",
    zipcode: "32114",
  },
  {
    id: "5fa09fef0e462ad3f35e8626",
    firstname: "James",
    lastname: "Jameson",
    email: "James@gmail.com",
    login: "James",
    password: "James1",
    zipcode: "32114",
  },
  {
    id: "5fa0a000f55aadbdab2a4b68",
    firstname: "Thomas",
    lastname: "Doe",
    email: "Thomas@gmail.com",
    login: "Thomas",
    password: "Thomas1",
    zipcode: "32114",
  },
  {
    id: "5fa0a0230e462ad3f35ea986",
    firstname: "Roscoe",
    lastname: "Feller",
    email: "Roscoe@gmail.com",
    login: "Roscoe1",
    password: "Roscoe1",
    zipcode: "32117",
  },
  {
    id: "5fa0a03259c60d68fa3e7b3a",
    firstname: "Spider",
    lastname: "Doggo",
    email: "Spider@gmail.com",
    login: "spider",
    password: "spider",
    zipcode: "32117",
  },
  {
    id: "5fa0a046cc4d8869c5333afd",
    firstname: "Jeffrey",
    lastname: "Jefferson",
    email: "Jeffrey@gmail.com",
    login: "Jeffrey",
    password: "Jeffrey1",
    zipcode: "32117",
  },
  {
    id: "5fa0a0518d170a713f7c0909",
    firstname: "Ronald",
    lastname: "Eaglin",
    email: "Ronald@gmail.com",
    login: "Eaglin",
    password: "Eaglin1",
    zipcode: "32117",
  },
  {
    id: "5f960f03e2f47d86b7e89d88",
    firstname: "Victor",
    lastname: "Zufelt",
    email: "victor@gmail.com",
    login: "Victor",
    password: "Victor1",
    zipcode: "32118",
  },
];

export const searchDatabase = [
  {
    userID: "5f95bc0bcf4c424ac739107f",
    id: "1",
    firstname: "Franco",
    lastname: "Mattos",
    email: "Franco@ohmnet.com",
    zipcode: "32116",
    itemname: "Couch",
    requests: [],
    traded: "No",
    about: "Red Sectional Couch\r\n",
  },
  {
    userID: "5f95bc0bcf4c424ac739107f",
    id: "2",
    firstname: "Franco",
    lastname: "Mattos",
    email: "Franco@ohmnet.com",
    zipcode: "32116",
    itemname: "Desk",
    requests: [],
    traded: "No",
    about: "Large Wood Desk\r\n",
  },
  {
    userID: "5f95bc0bcf4c424ac739107f",
    id: "3",
    firstname: "Franco",
    lastname: "Mattos",
    email: "Franco@ohmnet.com",
    zipcode: "32116",
    itemname: "Computer",
    requests: [],
    traded: "No",
    about: "Computer with Monitor\r\n",
  },
  {
    userID: "5f95bc0bcf4c424ac739107f",
    id: "4",
    firstname: "Franco",
    lastname: "Mattos",
    email: "Franco@ohmnet.com",
    zipcode: "32116",
    itemname: "Wallet",
    requests: [],
    traded: "No",
    about: "Leather bound wallet\r\n",
  },
  {
    userID: "5f95bc0bcf4c424ac739107f",
    id: "5",
    firstname: "Franco",
    lastname: "Mattos",
    email: "Franco@ohmnet.com",
    zipcode: "32116",
    itemname: "3D Printer",
    requests: [],
    traded: "No",
    about: "Prusa 3D Printer\r\n",
  },
  {
    userID: "5f95bc0bcf4c424ac739107f",
    id: "6",
    firstname: "Franco",
    lastname: "Mattos",
    email: "Franco@ohmnet.com",
    zipcode: "32116",
    itemname: "Mac Computer",
    requests: [],
    traded: "No",
    about: "A Mac Computer\r\n",
  },
  {
    userID: "5f95bc0bcf4c424ac739107f",
    id: "7",
    firstname: "Franco",
    lastname: "Mattos",
    email: "Franco@ohmnet.com",
    zipcode: "32116",
    itemname: "Soda",
    requests: [],
    traded: "No",
    about: "Soda\r\n",
  },
  {
    userID: "5f95bc0bcf4c424ac739107f",
    id: "8",
    firstname: "Franco",
    lastname: "Mattos",
    email: "Franco@ohmnet.com",
    zipcode: "32116",
    itemname: "Pikachu Plush",
    requests: [],
    traded: "No",
    about: "Pikachu Plush\r\n",
  },
  {
    userID: "5f95bc0bcf4c424ac739107f",
    id: "9",
    firstname: "Franco",
    lastname: "Mattos",
    email: "Franco@ohmnet.com",
    zipcode: "32116",
    itemname: "Falco Plush",
    requests: [],
    traded: "No",
    about: "Falco Plush\r\n",
  },
  {
    userID: "5f95bc0bcf4c424ac739107f",
    id: "10",
    firstname: "Franco",
    lastname: "Mattos",
    email: "Franco@ohmnet.com",
    zipcode: "32116",
    itemname: "Mona Lisa",
    requests: [],
    traded: "No",
    about: "Painting of Mona Lisa\r\n",
  },
  {
    userID: "5f95bc0bcf4c424ac739107f",
    id: "11",
    firstname: "Franco",
    lastname: "Mattos",
    email: "Franco@ohmnet.com",
    zipcode: "32116",
    itemname: "Monitor",
    requests: [],
    traded: "No",
    about: "4k 32in Monitor\r\n",
  },
  {
    userID: "5f95bc0bcf4c424ac739107f",
    id: "12",
    firstname: "Franco",
    lastname: "Mattos",
    email: "Franco@ohmnet.com",
    zipcode: "32116",
    itemname: "Jacket",
    requests: [],
    traded: "No",
    about: "Grey wool jacket\r\n",
  },
  {
    userID: "5f95bc0bcf4c424ac739107f",
    id: "13",
    firstname: "Franco",
    lastname: "Mattos",
    email: "Franco@ohmnet.com",
    zipcode: "32116",
    itemname: "Light Bulbs",
    requests: [],
    traded: "No",
    about: "25 Medium Light bulbs\r\n",
  },
  {
    userID: "5f960e6fcf4c424ac76de721",
    id: "14",
    firstname: "Donahue",
    lastname: "Morgan",
    email: "DMorgan@ohmnet.com",
    zipcode: "32116",
    itemname: "Glasses",
    requests: [],
    traded: "No",
    about: "Slightly used glasses\r\n",
  },
  {
    userID: "5f960e6fcf4c424ac76de721",
    id: "15",
    firstname: "Donahue",
    lastname: "Morgan",
    email: "DMorgan@ohmnet.com",
    zipcode: "32116",
    itemname: "Camera",
    requests: [],
    traded: "No",
    about: "Slightly used Camera\r\n",
  },
  {
    userID: "5f960e6fcf4c424ac76de721",
    id: "16",
    firstname: "Donahue",
    lastname: "Morgan",
    email: "DMorgan@ohmnet.com",
    zipcode: "32116",
    itemname: "Coasters",
    requests: [],
    traded: "No",
    about: "Black plastic coasters\r\n",
  },
  {
    userID: "5f960e6fcf4c424ac76de721",
    id: "17",
    firstname: "Donahue",
    lastname: "Morgan",
    email: "DMorgan@ohmnet.com",
    zipcode: "32116",
    itemname: "Pane of Glass",
    requests: [],
    traded: "No",
    about: "Glass for a window\r\n",
  },
  {
    userID: "5f960e6fcf4c424ac76de721",
    id: "18",
    firstname: "Donahue",
    lastname: "Morgan",
    email: "DMorgan@ohmnet.com",
    zipcode: "32116",
    itemname: "DND Minitures",
    requests: [],
    traded: "No",
    about: "A selection of Goblins and Orcs\r\n",
  },
  {
    userID: "5f960e6fcf4c424ac76de721",
    id: "19",
    firstname: "Donahue",
    lastname: "Morgan",
    email: "DMorgan@ohmnet.com",
    zipcode: "32116",
    itemname: "Pens",
    requests: [],
    traded: "No",
    about: "Lots of fancy pens\r\n",
  },
  {
    userID: "5f960e6fcf4c424ac76de721",
    id: "20",
    firstname: "Donahue",
    lastname: "Morgan",
    email: "DMorgan@ohmnet.com",
    zipcode: "32116",
    itemname: "Lamp",
    requests: [],
    traded: "No",
    about: "Might hold a genie\r\n",
  },
  {
    userID: "5f960e6fcf4c424ac76de721",
    id: "21",
    firstname: "Donahue",
    lastname: "Morgan",
    email: "DMorgan@ohmnet.com",
    zipcode: "32116",
    itemname: "TV Stand",
    requests: [],
    traded: "No",
    about: "Cherry wood TV Stand\r\n",
  },
  {
    userID: "5f960e6fcf4c424ac76de721",
    id: "22",
    firstname: "Donahue",
    lastname: "Morgan",
    email: "DMorgan@ohmnet.com",
    zipcode: "32116",
    itemname: "Play-pen",
    requests: [],
    traded: "No",
    about: "Play pen for a baby\r\n",
  },
  {
    userID: "5f960e6fcf4c424ac76de721",
    id: "23",
    firstname: "Donahue",
    lastname: "Morgan",
    email: "DMorgan@ohmnet.com",
    zipcode: "32116",
    itemname: "Chair",
    requests: [],
    traded: "No",
    about: "Oak wood chair\r\n",
  },
  {
    userID: "5f960e6fcf4c424ac76de721",
    id: "24",
    firstname: "Donahue",
    lastname: "Morgan",
    email: "DMorgan@ohmnet.com",
    zipcode: "32116",
    itemname: "Door",
    requests: [],
    traded: "No",
    about: "Front door for a house\r\n",
  },
  {
    userID: "5f960e6fcf4c424ac76de721",
    id: "25",
    firstname: "Donahue",
    lastname: "Morgan",
    email: "DMorgan@ohmnet.com",
    zipcode: "32116",
    itemname: "Tires",
    requests: [],
    traded: "No",
    about: "3 tires\r\n",
  },
  {
    userID: "5f960efacf4c424ac76e3b44",
    id: "26",
    firstname: "Nabeel",
    lastname: "Yousef",
    email: "nabeel_yousef@daytonastate.edu",
    zipcode: "32114",
    itemname: "Cups",
    requests: [],
    traded: "No",
    about: "Coffee Mugs\r\n",
  },
  {
    userID: "5f960efacf4c424ac76e3b44",
    id: "27",
    firstname: "Nabeel",
    lastname: "Yousef",
    email: "nabeel_yousef@daytonastate.edu",
    zipcode: "32114",
    itemname: "Desk Chair",
    requests: [],
    traded: "No",
    about: "Black Leather Desk Chair\r\n",
  },
  {
    userID: "5f960efacf4c424ac76e3b44",
    id: "28",
    firstname: "Nabeel",
    lastname: "Yousef",
    email: "nabeel_yousef@daytonastate.edu",
    zipcode: "32114",
    itemname: "Chips",
    requests: [],
    traded: "No",
    about: "Slightly stale chips\r\n",
  },
  {
    userID: "5f960efacf4c424ac76e3b44",
    id: "29",
    firstname: "Nabeel",
    lastname: "Yousef",
    email: "nabeel_yousef@daytonastate.edu",
    zipcode: "32114",
    itemname: "Shoes",
    requests: [],
    traded: "No",
    about: "Nikes size 11 shoes\r\n",
  },
  {
    userID: "5f960efacf4c424ac76e3b44",
    id: "30",
    firstname: "Nabeel",
    lastname: "Yousef",
    email: "nabeel_yousef@daytonastate.edu",
    zipcode: "32114",
    itemname: "Tree",
    requests: [],
    traded: "No",
    about: "Baby Palm Tree\r\n",
  },
  {
    userID: "5f960efacf4c424ac76e3b44",
    id: "31",
    firstname: "Nabeel",
    lastname: "Yousef",
    email: "nabeel_yousef@daytonastate.edu",
    zipcode: "32114",
    itemname: "Mailbox",
    requests: [],
    traded: "No",
    about: "White, metal mailbox with wood post\r\n",
  },
  {
    userID: "5f960efacf4c424ac76e3b44",
    id: "32",
    firstname: "Nabeel",
    lastname: "Yousef",
    email: "nabeel_yousef@daytonastate.edu",
    zipcode: "32114",
    itemname: "Home",
    requests: [],
    traded: "No",
    about: "3bed 2bath house\r\n",
  },
  {
    userID: "5f960efacf4c424ac76e3b44",
    id: "33",
    firstname: "Nabeel",
    lastname: "Yousef",
    email: "nabeel_yousef@daytonastate.edu",
    zipcode: "32114",
    itemname: "Stroller",
    requests: [],
    traded: "No",
    about: "Baby Stroller\r\n",
  },
  {
    userID: "5f960efacf4c424ac76e3b44",
    id: "34",
    firstname: "Nabeel",
    lastname: "Yousef",
    email: "nabeel_yousef@daytonastate.edu",
    zipcode: "32114",
    itemname: "Fan",
    requests: [],
    traded: "No",
    about: "Bronze/Brown ceiling fan\r\n",
  },
  {
    userID: "5fa09fef0e462ad3f35e8626",
    id: "35",
    firstname: "James",
    lastname: "Jameson",
    email: "James@gmail.com",
    zipcode: "32114",
    itemname: "Book",
    requests: [],
    traded: "No",
    about: "Hamlet play book\r\n",
  },
  {
    userID: "5fa09fef0e462ad3f35e8626",
    id: "36",
    firstname: "James",
    lastname: "Jameson",
    email: "James@gmail.com",
    zipcode: "32114",
    itemname: "Door Knob",
    requests: [],
    traded: "No",
    about: "Brushed Nickel Door Knob\r\n",
  },
  {
    userID: "5fa09fef0e462ad3f35e8626",
    id: "37",
    firstname: "James",
    lastname: "Jameson",
    email: "James@gmail.com",
    zipcode: "32114",
    itemname: "Planner",
    requests: [],
    traded: "No",
    about: "Planner from 2016\r\n",
  },
  {
    userID: "5fa09fef0e462ad3f35e8626",
    id: "38",
    firstname: "James",
    lastname: "Jameson",
    email: "James@gmail.com",
    zipcode: "32114",
    itemname: "High Chair",
    requests: [],
    traded: "No",
    about: "Baby High Chair\r\n",
  },
  {
    userID: "5fa09fef0e462ad3f35e8626",
    id: "39",
    firstname: "James",
    lastname: "Jameson",
    email: "James@gmail.com",
    zipcode: "32114",
    itemname: "Earbuds",
    requests: [],
    traded: "No",
    about: "Very used earbuds\r\n",
  },
  {
    userID: "5fa09fef0e462ad3f35e8626",
    id: "40",
    firstname: "James",
    lastname: "Jameson",
    email: "James@gmail.com",
    zipcode: "32114",
    itemname: "Headset",
    requests: [],
    traded: "No",
    about: "A razor headset\r\n",
  },
  {
    userID: "5fa09fef0e462ad3f35e8626",
    id: "41",
    firstname: "James",
    lastname: "Jameson",
    email: "James@gmail.com",
    zipcode: "32114",
    itemname: "Switch Controller",
    requests: [],
    traded: "No",
    about: "Nintendo Switch Controller\r\n",
  },
  {
    userID: "5fa09fef0e462ad3f35e8626",
    id: "42",
    firstname: "James",
    lastname: "Jameson",
    email: "James@gmail.com",
    zipcode: "32114",
    itemname: "Player Handbook",
    requests: [],
    traded: "No",
    about: "DND Player Handbook\r\n",
  },
  {
    userID: "5fa09fef0e462ad3f35e8626",
    id: "43",
    firstname: "James",
    lastname: "Jameson",
    email: "James@gmail.com",
    zipcode: "32114",
    itemname: "Sweaters",
    requests: [],
    traded: "No",
    about: "5 Wool Sweaters\r\n",
  },
  {
    userID: "5fa0a000f55aadbdab2a4b68",
    id: "44",
    firstname: "Thomas",
    lastname: "Doe",
    email: "Thomas@gmail.com",
    zipcode: "32114",
    itemname: "Soccer Ball",
    requests: [],
    traded: "No",
    about: "Soccer Ball\r\n",
  },
  {
    userID: "5fa0a000f55aadbdab2a4b68",
    id: "45",
    firstname: "Thomas",
    lastname: "Doe",
    email: "Thomas@gmail.com",
    zipcode: "32114",
    itemname: "Jeans",
    requests: [],
    traded: "No",
    about: "5 Blue Jeans\r\n",
  },
  {
    userID: "5fa0a000f55aadbdab2a4b68",
    id: "46",
    firstname: "Thomas",
    lastname: "Doe",
    email: "Thomas@gmail.com",
    zipcode: "32114",
    itemname: "Air Freshener",
    requests: [],
    traded: "No",
    about: "Cherry Scented Air Freshener\r\n",
  },
  {
    userID: "5fa0a000f55aadbdab2a4b68",
    id: "47",
    firstname: "Thomas",
    lastname: "Doe",
    email: "Thomas@gmail.com",
    zipcode: "32114",
    itemname: "Baby Monitor",
    requests: [],
    traded: "No",
    about: "Baby Monitor with camera\r\n",
  },
  {
    userID: "5fa0a000f55aadbdab2a4b68",
    id: "48",
    firstname: "Thomas",
    lastname: "Doe",
    email: "Thomas@gmail.com",
    zipcode: "32114",
    itemname: "PLA",
    requests: [],
    traded: "No",
    about: "PLA 1kg 1.75mm thick\r\n",
  },
  {
    userID: "5fa0a000f55aadbdab2a4b68",
    id: "49",
    firstname: "Thomas",
    lastname: "Doe",
    email: "Thomas@gmail.com",
    zipcode: "32114",
    itemname: "Speaker",
    requests: [],
    traded: "No",
    about: "New Mini Speaker\r\n",
  },
  {
    userID: "5fa0a000f55aadbdab2a4b68",
    id: "50",
    firstname: "Thomas",
    lastname: "Doe",
    email: "Thomas@gmail.com",
    zipcode: "32114",
    itemname: "Phone",
    requests: [],
    traded: "No",
    about: "Galaxy Pro\r\n",
  },
  {
    userID: "5fa0a000f55aadbdab2a4b68",
    id: "51",
    firstname: "Thomas",
    lastname: "Doe",
    email: "Thomas@gmail.com",
    zipcode: "32114",
    itemname: "Lawn Mower",
    requests: [],
    traded: "No",
    about: "Push Lawn Mower, slightly used\r\n",
  },
  {
    userID: "5fa0a000f55aadbdab2a4b68",
    id: "52",
    firstname: "Thomas",
    lastname: "Doe",
    email: "Thomas@gmail.com",
    zipcode: "32114",
    itemname: "Dog Toys",
    requests: [],
    traded: "No",
    about: "Assortment of dog toys\r\n",
  },
  {
    userID: "5fa0a0230e462ad3f35ea986",
    id: "53",
    firstname: "Roscoe",
    lastname: "Feller",
    email: "Roscoe@gmail.com",
    zipcode: "32117",
    itemname: "Micro SD Card",
    requests: [],
    traded: "No",
    about: "16GB Micro SD Card\r\n",
  },
  {
    userID: "5fa0a0230e462ad3f35ea986",
    id: "54",
    firstname: "Roscoe",
    lastname: "Feller",
    email: "Roscoe@gmail.com",
    zipcode: "32117",
    itemname: "Hand Lotion",
    requests: [],
    traded: "No",
    about: "Aloe Hand Lotion\r\n",
  },
  {
    userID: "5fa0a0230e462ad3f35ea986",
    id: "55",
    firstname: "Roscoe",
    lastname: "Feller",
    email: "Roscoe@gmail.com",
    zipcode: "32117",
    itemname: "Crocs",
    requests: [],
    traded: "No",
    about: "Black, size 10 crocs\r\n",
  },
  {
    userID: "5fa0a0230e462ad3f35ea986",
    id: "56",
    firstname: "Roscoe",
    lastname: "Feller",
    email: "Roscoe@gmail.com",
    zipcode: "32117",
    itemname: "Purse",
    requests: [],
    traded: "No",
    about: "Louis Vuitton Purse\r\n",
  },
  {
    userID: "5fa0a0230e462ad3f35ea986",
    id: "57",
    firstname: "Roscoe",
    lastname: "Feller",
    email: "Roscoe@gmail.com",
    zipcode: "32117",
    itemname: "Watch",
    requests: [],
    traded: "No",
    about: "Mens Casio Vintage Watch\r\n",
  },
  {
    userID: "5fa0a0230e462ad3f35ea986",
    id: "58",
    firstname: "Roscoe",
    lastname: "Feller",
    email: "Roscoe@gmail.com",
    zipcode: "32117",
    itemname: "W.o.W. Subscription",
    requests: [],
    traded: "No",
    about: "60 Day world of warcraft sub card\r\n",
  },
  {
    userID: "5fa0a03259c60d68fa3e7b3a",
    id: "59",
    firstname: "Spider",
    lastname: "Doggo",
    email: "Spider@gmail.com",
    zipcode: "32117",
    itemname: "DVD Player",
    requests: [],
    traded: "No",
    about: "DVD Player, 3 years old\r\n",
  },
  {
    userID: "5fa0a03259c60d68fa3e7b3a",
    id: "60",
    firstname: "Spider",
    lastname: "Doggo",
    email: "Spider@gmail.com",
    zipcode: "32117",
    itemname: "Playstation",
    requests: [],
    traded: "No",
    about: "Playstation 4 game console\r\n",
  },
  {
    userID: "5fa0a03259c60d68fa3e7b3a",
    id: "61",
    firstname: "Spider",
    lastname: "Doggo",
    email: "Spider@gmail.com",
    zipcode: "32117",
    itemname: "Xbox",
    requests: [],
    traded: "No",
    about: "XBOX X game console\r\n",
  },
  {
    userID: "5fa0a03259c60d68fa3e7b3a",
    id: "62",
    firstname: "Spider",
    lastname: "Doggo",
    email: "Spider@gmail.com",
    zipcode: "32117",
    itemname: "Leash",
    requests: [],
    traded: "No",
    about: "Dog leash, 3ft long, green\r\n",
  },
  {
    userID: "5fa0a03259c60d68fa3e7b3a",
    id: "63",
    firstname: "Spider",
    lastname: "Doggo",
    email: "Spider@gmail.com",
    zipcode: "32117",
    itemname: "Tea Pot",
    requests: [],
    traded: "No",
    about: "Vintage tea pot from England\r\n",
  },
  {
    userID: "5fa0a03259c60d68fa3e7b3a",
    id: "64",
    firstname: "Spider",
    lastname: "Doggo",
    email: "Spider@gmail.com",
    zipcode: "32117",
    itemname: "Barbie",
    requests: [],
    traded: "No",
    about: "2000 Special Edition Barbie\r\n",
  },
  {
    userID: "5fa0a046cc4d8869c5333afd",
    id: "65",
    firstname: "Jeffrey",
    lastname: "Jefferson",
    email: "Jeffrey@gmail.com",
    zipcode: "32117",
    itemname: "DVD",
    requests: [],
    traded: "No",
    about: "Baby shark DVD\r\n",
  },
  {
    userID: "5fa0a046cc4d8869c5333afd",
    id: "66",
    firstname: "Jeffrey",
    lastname: "Jefferson",
    email: "Jeffrey@gmail.com",
    zipcode: "32117",
    itemname: "Coloring books",
    requests: [],
    traded: "No",
    about: "5 Coloring books\r\n",
  },
  {
    userID: "5fa0a046cc4d8869c5333afd",
    id: "67",
    firstname: "Jeffrey",
    lastname: "Jefferson",
    email: "Jeffrey@gmail.com",
    zipcode: "32117",
    itemname: "Treadmill",
    requests: [],
    traded: "No",
    about: "Home treadmill\r\n",
  },
  {
    userID: "5fa0a046cc4d8869c5333afd",
    id: "68",
    firstname: "Jeffrey",
    lastname: "Jefferson",
    email: "Jeffrey@gmail.com",
    zipcode: "32117",
    itemname: "Succulents",
    requests: [],
    traded: "No",
    about: "3 Succulents\r\n",
  },
  {
    userID: "5fa0a046cc4d8869c5333afd",
    id: "69",
    firstname: "Jeffrey",
    lastname: "Jefferson",
    email: "Jeffrey@gmail.com",
    zipcode: "32117",
    itemname: "Weed Eater",
    requests: [],
    traded: "No",
    about: "Weed Eater\r\n",
  },
  {
    userID: "5fa0a046cc4d8869c5333afd",
    id: "70",
    firstname: "Jeffrey",
    lastname: "Jefferson",
    email: "Jeffrey@gmail.com",
    zipcode: "32117",
    itemname: "Nail gun",
    requests: [],
    traded: "No",
    about: "slightly used nail gun\r\n",
  },
  {
    userID: "5fa0a0518d170a713f7c0909",
    id: "71",
    firstname: "Ronald",
    lastname: "Eaglin",
    email: "Ronald@gmail.com",
    zipcode: "32117",
    itemname: "Surf Board",
    requests: [],
    traded: "No",
    about: "Red, surf board with channeled bottom\r\n",
  },
  {
    userID: "5fa0a0518d170a713f7c0909",
    id: "72",
    firstname: "Ronald",
    lastname: "Eaglin",
    email: "Ronald@gmail.com",
    zipcode: "32117",
    itemname: "Guitar",
    requests: [],
    traded: "No",
    about: "Blue, with flames guitar\r\n",
  },
  {
    userID: "5fa0a0518d170a713f7c0909",
    id: "73",
    firstname: "Ronald",
    lastname: "Eaglin",
    email: "Ronald@gmail.com",
    zipcode: "32117",
    itemname: "Trailer Hitch",
    requests: [],
    traded: "No",
    about: "Universal Trailer Hitch\r\n",
  },
  {
    userID: "5fa0a0518d170a713f7c0909",
    id: "74",
    firstname: "Ronald",
    lastname: "Eaglin",
    email: "Ronald@gmail.com",
    zipcode: "32117",
    itemname: "Training Potty",
    requests: [],
    traded: "No",
    about: "Training potty for child\r\n",
  },
  {
    userID: "5fa0a0518d170a713f7c0909",
    id: "75",
    firstname: "Ronald",
    lastname: "Eaglin",
    email: "Ronald@gmail.com",
    zipcode: "32117",
    itemname: "Dog house",
    requests: [],
    traded: "No",
    about: "brown dog house with shingled roof\r\n",
  },
  {
    userID: "5fa0a0518d170a713f7c0909",
    id: "76",
    firstname: "Ronald",
    lastname: "Eaglin",
    email: "Ronald@gmail.com",
    zipcode: "32117",
    itemname: "Kayak paddle",
    requests: [],
    traded: "No",
    about: "Just paddle, no kayak\r\n",
  },
];
